import express from 'express';
import cors from 'cors';
import dotenv from 'dotenv';
import ccxt from 'ccxt';
dotenv.config();
const app = express();
const PORT = process.env.PORT || 3000;
app.use(cors());
app.use(express.json());
app.get('/api/health', (req, res) => res.json({ status: 'ok', message: 'Ready' }));
app.post('/api/webhook/tradingview', async (req, res) => res.status(200).json({ status: 'success' }));
app.listen(PORT, () => console.log('Server is running on port ' + PORT));
